require: rubocop-rails

AllCops:
  Exclude:
    - "config/initializers/*"
    - 'config/environments/*'
    - 'config/application.rb'
    - "db/schema.rb"
    - "node_modules/**/*"
    - "db/migrate/*.rb"
    - "bin/*"
  TargetRubyVersion: 2.6.3

# --- Style --- #

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

# --- Metrics --- #
Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'spec/**/**/*'

Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 15