version: 2.1

executors:
  directory_settings:
    working_directory: ~/my_app

orbs:
  ruby: circleci/ruby@1.0.0
  node: circleci/node@2 

jobs:
  build:
    executor: directory_settings
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
    steps:
      - checkout
      - ruby/install-deps
      # Store bundle cache
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"

  test:
    executor: directory_settings
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USERNAME: 'root'
          MYSQL_PASSWORD: ''
          MYSQL_PORT: 3306
          MYSQL_HOST: 127.0.0.1
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      RAILS_ENV: test

    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: DB config settings
          command: mv config/database.yml.ci config/database.yml
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rake db:create db:schema:load --trace
      - run: bundle exec bin/webpack
      # Run rspec in parallel
      - ruby/rspec-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
