version: 2.1

executors:
  directory_settings:
    working_directory: ~/my_app

orbs:
  ruby: circleci/ruby@1.0

jobs:
  checkout_code:
    executor: directory_settings
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project

  test:
    executor: directory_settings
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USERNAME: 'root'
          MYSQL_PASSWORD: ''
          MYSQL_PORT: 3306
          MYSQL_HOST: 127.0.0.1
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      RAILS_ENV: test

    steps:
      - checkout
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - ruby/install-deps
      - run:
          name: nodejs install
          command: |
            curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run: yarn install --check-files
      - save_cache:
          paths:
            - ./vendor/bundle
            - ./node_modules
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
      - run:
          name: DB config settings
          command: mv config/database.yml.ci config/database.yml
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rake db:create db:schema:load --trace
      - run: 
          name: Start Webpack
          command: bundle exec bin/webpack

      - run: bundle exec rubocop
      - run: bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
